# Generated by Django 5.0.6 on 2024-06-25 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 2, 16, 40, 44, 420444)),
        ),
    ]
