# Generated by Django 5.0.6 on 2024-07-03 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_banner_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 10, 21, 3, 34, 352470)),
        ),
    ]
